name: Pranav Maddi
description: Musings on things
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: true
logo: false
paginate: 15

# Details for the RSS feed generator
url: http://pranavmaddi.com
author: 'Pranav Maddi'
bio: Pranav likes to write software and build businesses
