name: Pranav Maddi
description: I made a blog
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: true
logo: false
paginate: 15

# Details for the RSS feed generator
url: http://pranavmaddi.com
author: 'Pranav Maddi'
bio: Pranav is an intern at Facebook for the summer of 2015 and a CS major at Yale.