name: Pranav
description: The wonderful world of Pranav
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url: http://pranavmaddi.com
author: 'Pranav Maddi'
bio: Yale CS major and Mozilla intern